language: ruby
bundler_args: --without development

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode

env:
  - PATTERN=keen
  - PATTERN=integration KEEN_MASTER_KEY=f806128f31c349fda124b62d1f4cf4b2 KEEN_WRITE_KEY=f806128f31c349fda124b62d1f4cf4b2 KEEN_READ_KEY=f806128f31c349fda124b62d1f4cf4b2 KEEN_PROJECT_ID=50e5ffa6897a2c319b000000
  - PATTERN=synchrony

matrix:
  exclude:
    - rvm: 1.8.7
      env: PATTERN=synchrony
    - rvm: jruby-19mode
      env: PATTERN=synchrony

script:
  - bundle exec rake pattern
